package engine

import "fmt"

// UnboundConfigTemplate is the text/template string for generating unbound.conf.
const UnboundConfigTemplate = `server:
    interface: {{.ListenAddr}}
    port: {{.ListenPort}}
    do-daemonize: no
    use-syslog: no
    log-queries: no
    msg-cache-size: {{.MsgCacheSize}}
    rrset-cache-size: {{.RrsetCacheSize}}
    cache-min-ttl: {{.Cache.PositiveTtlMin}}
    cache-max-ttl: {{.Cache.PositiveTtlMax}}
    cache-max-negative-ttl: {{.Cache.NegativeTtl}}
    prefetch: {{if .Cache.PrefetchEnabled}}yes{{else}}no{{end}}
    serve-expired: yes
    num-threads: 2
    access-control: 127.0.0.0/8 allow
    access-control: 10.0.0.0/8 allow
    access-control: 172.16.0.0/12 allow
    access-control: 192.168.0.0/16 allow

forward-zone:
    name: "."
{{- range .Upstreams}}
    forward-addr: {{.Address}}{{if ne .Port 53}}@{{.Port}}{{end}}
{{- end}}
`

// CorefileTemplate is the text/template string for generating a CoreDNS Corefile.
const CorefileTemplate = `.:{{.ListenPort}} {
    bind {{.ListenAddr}}
    forward . {{range .Upstreams}}{{.Address}}:{{.Port}} {{end}}{
        policy sequential
    }
    cache {{.Cache.PositiveTtlMax}} {
        success {{.Cache.MaxEntries}} {{.Cache.PositiveTtlMax}}
        denial {{.Cache.MaxEntries}} {{.Cache.NegativeTtl}}
{{- if .Cache.PrefetchEnabled}}
        prefetch {{.Cache.PrefetchThreshold}} 1h 10%
{{- end}}
    }
    reload 5s
    errors
    log
}
`

// RecursorConfTemplate is the text/template string for generating PowerDNS recursor.conf.
const RecursorConfTemplate = `# PowerDNS Recursor configuration — generated by AstraDNS
local-address={{.ListenAddr}}
local-port={{.ListenPort}}
daemon=no
write-pid=no
disable-syslog=yes
log-common-errors=yes
threads=2
max-cache-entries={{.Cache.MaxEntries}}
max-negative-ttl={{.Cache.NegativeTtl}}
max-cache-ttl={{.Cache.PositiveTtlMax}}
forward-zones=.={{.ForwardAddresses}}
allow-from=127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
`

// TemplateData extends EngineConfig with computed fields for template rendering.
type TemplateData struct {
	EngineConfig

	// MsgCacheSize is the Unbound msg-cache-size derived from MaxEntries.
	MsgCacheSize string
	// RrsetCacheSize is the Unbound rrset-cache-size (2x msg-cache-size).
	RrsetCacheSize string
	// ForwardAddresses is the PowerDNS semicolon-separated upstream list (e.g., "1.1.1.1:53;8.8.8.8:53").
	ForwardAddresses string
}

// NewTemplateData creates a TemplateData from an EngineConfig with computed fields.
func NewTemplateData(config EngineConfig) TemplateData {
	// Calculate Unbound cache sizes
	msgCacheBytes := config.Cache.MaxEntries * 1024
	if msgCacheBytes > 256*1024*1024 {
		msgCacheBytes = 256 * 1024 * 1024
	}
	rrsetCacheBytes := msgCacheBytes * 2

	// Build PowerDNS forward addresses
	var forwardAddrs string
	for i, u := range config.Upstreams {
		port := u.Port
		if port == 0 {
			port = 53
		}
		if i > 0 {
			forwardAddrs += ";"
		}
		forwardAddrs += fmt.Sprintf("%s:%d", u.Address, port)
	}

	return TemplateData{
		EngineConfig:     config,
		MsgCacheSize:     formatBytes(msgCacheBytes),
		RrsetCacheSize:   formatBytes(rrsetCacheBytes),
		ForwardAddresses: forwardAddrs,
	}
}

func formatBytes(bytes int) string {
	if bytes >= 1024*1024 {
		return fmt.Sprintf("%dm", bytes/(1024*1024))
	}
	return fmt.Sprintf("%dk", bytes/1024)
}
