package engine

import (
	"fmt"
	"math"
	"net/netip"
	"strings"
)

const (
	kilobyte = int64(1024)
	megabyte = kilobyte * 1024

	maxMsgCacheBytes = 256 * megabyte
)

// UnboundConfigTemplate is the text/template string for generating unbound.conf.
const UnboundConfigTemplate = `server:
    interface: {{.ListenAddr}}
    port: {{.ListenPort}}
    do-daemonize: no
    use-syslog: no
    log-queries: no
    msg-cache-size: {{.MsgCacheSize}}
    rrset-cache-size: {{.RrsetCacheSize}}
    cache-min-ttl: {{.Cache.PositiveTtlMin}}
    cache-max-ttl: {{.Cache.PositiveTtlMax}}
    cache-max-negative-ttl: {{.Cache.NegativeTtl}}
    prefetch: {{if .Cache.PrefetchEnabled}}yes{{else}}no{{end}}
    serve-expired: yes
    num-threads: 2
    access-control: 127.0.0.0/8 allow
    access-control: 10.0.0.0/8 allow
    access-control: 172.16.0.0/12 allow
    access-control: 192.168.0.0/16 allow

forward-zone:
    name: "."
{{- range .Upstreams}}
    forward-addr: {{.Address}}{{if ne .Port 53}}@{{.Port}}{{end}}
{{- end}}
`

// CorefileTemplate is the text/template string for generating a CoreDNS Corefile.
const CorefileTemplate = `.:{{.ListenPort}} {
    bind {{.ListenAddr}}
    forward . {{range .Upstreams}}{{.Address}}:{{.Port}} {{end}}{
        policy sequential
    }
    cache {{.Cache.PositiveTtlMax}} {
        success {{.Cache.MaxEntries}} {{.Cache.PositiveTtlMax}}
        denial {{.Cache.MaxEntries}} {{.Cache.NegativeTtl}}
{{- if .Cache.PrefetchEnabled}}
        prefetch {{.Cache.PrefetchThreshold}} 1h 10%
{{- end}}
    }
    reload 5s
    errors
    log
}
`

// RecursorConfTemplate is the text/template string for generating PowerDNS recursor.conf.
const RecursorConfTemplate = `# PowerDNS Recursor configuration — generated by AstraDNS
local-address={{.ListenAddr}}
local-port={{.ListenPort}}
daemon=no
write-pid=no
disable-syslog=yes
log-common-errors=yes
threads=2
max-cache-entries={{.Cache.MaxEntries}}
max-negative-ttl={{.Cache.NegativeTtl}}
minimum-ttl-override={{.Cache.PositiveTtlMin}}
max-cache-ttl={{.Cache.PositiveTtlMax}}
forward-zones=.={{.ForwardAddresses}}
allow-from=127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
`

// TemplateData extends EngineConfig with computed fields for template rendering.
type TemplateData struct {
	EngineConfig

	// MsgCacheSize is the Unbound msg-cache-size derived from MaxEntries.
	MsgCacheSize string
	// RrsetCacheSize is the Unbound rrset-cache-size (2x msg-cache-size).
	RrsetCacheSize string
	// ForwardAddresses is the PowerDNS semicolon-separated upstream list (e.g., "1.1.1.1:53;8.8.8.8:53").
	ForwardAddresses string
}

// NewTemplateData creates a TemplateData from an EngineConfig with computed fields.
func NewTemplateData(config EngineConfig) TemplateData {
	normalized := normalizeTemplateConfig(config)

	// Calculate Unbound cache sizes
	msgCacheBytes := int64(normalized.Cache.MaxEntries)
	if msgCacheBytes < 0 {
		msgCacheBytes = 0
	}
	msgCacheBytes *= kilobyte
	if msgCacheBytes > maxMsgCacheBytes {
		msgCacheBytes = maxMsgCacheBytes
	}
	rrsetCacheBytes := msgCacheBytes * 2

	// Build PowerDNS forward addresses
	var forwardAddrs string
	for i, u := range normalized.Upstreams {
		port := u.Port
		if port == 0 {
			port = 53
		}
		if i > 0 {
			forwardAddrs += ";"
		}
		forwardAddrs += fmt.Sprintf("%s:%d", u.Address, port)
	}

	return TemplateData{
		EngineConfig:     normalized,
		MsgCacheSize:     formatBytes(msgCacheBytes),
		RrsetCacheSize:   formatBytes(rrsetCacheBytes),
		ForwardAddresses: forwardAddrs,
	}
}

func normalizeTemplateConfig(config EngineConfig) EngineConfig {
	normalized := config
	normalized.ListenAddr = sanitizeTemplateValue(normalized.ListenAddr)
	normalized.Upstreams = make([]UpstreamConfig, len(config.Upstreams))
	for i := range config.Upstreams {
		normalized.Upstreams[i] = config.Upstreams[i]
		normalized.Upstreams[i].Address = sanitizeTemplateValue(config.Upstreams[i].Address)
	}

	return normalized
}

func sanitizeTemplateValue(value string) string {
	trimmed := strings.TrimSpace(value)
	return strings.Map(func(r rune) rune {
		if r < 32 || r == 127 {
			return -1
		}
		return r
	}, trimmed)
}

// ValidateTemplateConfig validates addresses before rendering configuration templates.
func ValidateTemplateConfig(config EngineConfig) error {
	if err := validateTemplateAddress(config.ListenAddr, "listenAddr"); err != nil {
		return err
	}

	for i, upstream := range config.Upstreams {
		field := fmt.Sprintf("upstreams[%d].address", i)
		if err := validateTemplateAddress(upstream.Address, field); err != nil {
			return err
		}
	}

	return nil
}

func validateTemplateAddress(value, field string) error {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return fmt.Errorf("%s is required", field)
	}

	for _, r := range trimmed {
		if r < 32 || r == 127 {
			return fmt.Errorf("%s contains control characters", field)
		}
	}

	if _, err := netip.ParseAddr(trimmed); err == nil {
		return nil
	}

	if isValidHostname(trimmed) {
		return nil
	}

	return fmt.Errorf("%s must be a valid IP address or DNS hostname", field)
}

func isValidHostname(host string) bool {
	name := strings.TrimSuffix(host, ".")
	if name == "" || len(name) > 253 {
		return false
	}

	labels := strings.Split(name, ".")
	for _, label := range labels {
		if len(label) == 0 || len(label) > 63 {
			return false
		}
		for i := 0; i < len(label); i++ {
			b := label[i]
			isAlpha := b >= 'a' && b <= 'z' || b >= 'A' && b <= 'Z'
			isDigit := b >= '0' && b <= '9'
			if !isAlpha && !isDigit && b != '-' {
				return false
			}
			if (i == 0 || i == len(label)-1) && b == '-' {
				return false
			}
		}
	}

	return true
}

func formatBytes(bytes int64) string {
	if bytes >= megabyte {
		value := int64(math.Ceil(float64(bytes) / float64(megabyte)))
		return fmt.Sprintf("%dm", value)
	}

	value := int64(math.Ceil(float64(bytes) / float64(kilobyte)))
	return fmt.Sprintf("%dk", value)
}
