//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSCacheProfile) DeepCopyInto(out *DNSCacheProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSCacheProfile.
func (in *DNSCacheProfile) DeepCopy() *DNSCacheProfile {
	if in == nil {
		return nil
	}
	out := new(DNSCacheProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSCacheProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSCacheProfileList) DeepCopyInto(out *DNSCacheProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DNSCacheProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSCacheProfileList.
func (in *DNSCacheProfileList) DeepCopy() *DNSCacheProfileList {
	if in == nil {
		return nil
	}
	out := new(DNSCacheProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSCacheProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSCacheProfileSpec) DeepCopyInto(out *DNSCacheProfileSpec) {
	*out = *in
	out.PositiveTtl = in.PositiveTtl
	out.NegativeTtl = in.NegativeTtl
	out.Prefetch = in.Prefetch
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSCacheProfileSpec.
func (in *DNSCacheProfileSpec) DeepCopy() *DNSCacheProfileSpec {
	if in == nil {
		return nil
	}
	out := new(DNSCacheProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSCacheProfileStatus) DeepCopyInto(out *DNSCacheProfileStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSCacheProfileStatus.
func (in *DNSCacheProfileStatus) DeepCopy() *DNSCacheProfileStatus {
	if in == nil {
		return nil
	}
	out := new(DNSCacheProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSUpstreamPool) DeepCopyInto(out *DNSUpstreamPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSUpstreamPool.
func (in *DNSUpstreamPool) DeepCopy() *DNSUpstreamPool {
	if in == nil {
		return nil
	}
	out := new(DNSUpstreamPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSUpstreamPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSUpstreamPoolList) DeepCopyInto(out *DNSUpstreamPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DNSUpstreamPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSUpstreamPoolList.
func (in *DNSUpstreamPoolList) DeepCopy() *DNSUpstreamPoolList {
	if in == nil {
		return nil
	}
	out := new(DNSUpstreamPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSUpstreamPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSUpstreamPoolSpec) DeepCopyInto(out *DNSUpstreamPoolSpec) {
	*out = *in
	if in.Upstreams != nil {
		in, out := &in.Upstreams, &out.Upstreams
		*out = make([]Upstream, len(*in))
		copy(*out, *in)
	}
	out.HealthCheck = in.HealthCheck
	out.LoadBalancing = in.LoadBalancing
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSUpstreamPoolSpec.
func (in *DNSUpstreamPoolSpec) DeepCopy() *DNSUpstreamPoolSpec {
	if in == nil {
		return nil
	}
	out := new(DNSUpstreamPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSUpstreamPoolStatus) DeepCopyInto(out *DNSUpstreamPoolStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UpstreamStatuses != nil {
		in, out := &in.UpstreamStatuses, &out.UpstreamStatuses
		*out = make([]UpstreamStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSUpstreamPoolStatus.
func (in *DNSUpstreamPoolStatus) DeepCopy() *DNSUpstreamPoolStatus {
	if in == nil {
		return nil
	}
	out := new(DNSUpstreamPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalDNSPolicy) DeepCopyInto(out *ExternalDNSPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalDNSPolicy.
func (in *ExternalDNSPolicy) DeepCopy() *ExternalDNSPolicy {
	if in == nil {
		return nil
	}
	out := new(ExternalDNSPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExternalDNSPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalDNSPolicyList) DeepCopyInto(out *ExternalDNSPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ExternalDNSPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalDNSPolicyList.
func (in *ExternalDNSPolicyList) DeepCopy() *ExternalDNSPolicyList {
	if in == nil {
		return nil
	}
	out := new(ExternalDNSPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExternalDNSPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalDNSPolicySpec) DeepCopyInto(out *ExternalDNSPolicySpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	out.UpstreamPoolRef = in.UpstreamPoolRef
	out.CacheProfileRef = in.CacheProfileRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalDNSPolicySpec.
func (in *ExternalDNSPolicySpec) DeepCopy() *ExternalDNSPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ExternalDNSPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalDNSPolicyStatus) DeepCopyInto(out *ExternalDNSPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalDNSPolicyStatus.
func (in *ExternalDNSPolicyStatus) DeepCopy() *ExternalDNSPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ExternalDNSPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckConfig) DeepCopyInto(out *HealthCheckConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckConfig.
func (in *HealthCheckConfig) DeepCopy() *HealthCheckConfig {
	if in == nil {
		return nil
	}
	out := new(HealthCheckConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancingConfig) DeepCopyInto(out *LoadBalancingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancingConfig.
func (in *LoadBalancingConfig) DeepCopy() *LoadBalancingConfig {
	if in == nil {
		return nil
	}
	out := new(LoadBalancingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NegTtlConfig) DeepCopyInto(out *NegTtlConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NegTtlConfig.
func (in *NegTtlConfig) DeepCopy() *NegTtlConfig {
	if in == nil {
		return nil
	}
	out := new(NegTtlConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicySelector) DeepCopyInto(out *PolicySelector) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicySelector.
func (in *PolicySelector) DeepCopy() *PolicySelector {
	if in == nil {
		return nil
	}
	out := new(PolicySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrefetchConfig) DeepCopyInto(out *PrefetchConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrefetchConfig.
func (in *PrefetchConfig) DeepCopy() *PrefetchConfig {
	if in == nil {
		return nil
	}
	out := new(PrefetchConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRef) DeepCopyInto(out *ResourceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRef.
func (in *ResourceRef) DeepCopy() *ResourceRef {
	if in == nil {
		return nil
	}
	out := new(ResourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TtlConfig) DeepCopyInto(out *TtlConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TtlConfig.
func (in *TtlConfig) DeepCopy() *TtlConfig {
	if in == nil {
		return nil
	}
	out := new(TtlConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Upstream) DeepCopyInto(out *Upstream) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Upstream.
func (in *Upstream) DeepCopy() *Upstream {
	if in == nil {
		return nil
	}
	out := new(Upstream)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamStatus) DeepCopyInto(out *UpstreamStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamStatus.
func (in *UpstreamStatus) DeepCopy() *UpstreamStatus {
	if in == nil {
		return nil
	}
	out := new(UpstreamStatus)
	in.DeepCopyInto(out)
	return out
}
